name: Auto Comment
on: [issues]
jobs:
  run:
    if: startsWith(github.event.issue.title, '[bug]')
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}
            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible. is labelled ${{ join(github.event.issue.labels.*.name, ', ') }}
            
            contains ${{ contains(github.event.issue.labels.*.name, 'bug') }}
            
            title : ${{ github.event.issue.title }}
            title contains ${{ contains(github.event.issue.title, '[bug]') }}
            title starts with [bug] ${{ startsWith(github.event.issue.title, '[bug]') }}
            condition to check if the issue is lablled with bug ${{ contains(github.event.issue.labels.*.name, 'bug') }}
            
            more infor here https://docs.github.com/en/actions/learn-github-actions/expressions
